# Generated by Django 5.0.3 on 2024-04-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='floor_name',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
