# Generated by Django 5.0.3 on 2024-04-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_floor_floor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='floor_planning',
            field=models.ImageField(blank=True, null=True, upload_to='floor'),
        ),
    ]
