# Generated by Django 5.0.3 on 2024-04-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_alter_room_room_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='floor',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='room',
            name='is_bookable',
            field=models.BooleanField(default=True),
        ),
    ]
