# Generated by Django 5.0.3 on 2024-04-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_remove_booking_user_booking_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
