# Generated by Django 5.0.3 on 2024-04-02 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_timeslot_alter_booking_room_booking_timeslot_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['id']},
        ),
    ]
