# Generated by Django 5.0.3 on 2024-04-02 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_alter_timeslot_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='timeslot',
        ),
    ]
