# Generated by Django 5.0.3 on 2024-04-02 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0013_timeslot_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='available_timeslots',
            new_name='booked_slots',
        ),
    ]
